# Generated by Django 6.0 on 2025-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gd", "0002_remove_income_date_income_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="next_disbursement",
            field=models.DateField(blank=True, null=True),
        ),
    ]
